/**
 * @description Handles team registration commands and user enrollment processes
 * @author A. Rahman Syed
 * @github legendhimself
 * @version 1.0.0
 *
 * This file is part of the E-Cell Hackathon Discord bot.
 * For questions or issues, please contact the maintainers at:
 * https://github.com/E-Cell-MJCET
 */

// List of team names for the hackathon
// Names are sorted and de-duplicated, with proper casing
export const teamNames = [
  'AdaCode',
  'The Helmetica',
  'invesTechs',
  'BitsnBytes',
  'Innoverse',
  'Code walkers',
  'SIX EYES',
  'Xchange Minds',
  'MindStack',
  'The Falcons',
  // 'Hacker',
  // 'Nexus',
  // 'Ignition',
  // 'Team Hypnosis',
  // 'MysticMinds',
  // 'EmbedX',
  // 'Team Liege',
  // 'Tech Titans',
  // 'Gazi - The Warrior',
  // 'N+1',
  // 'Ctrl Freaks',
  // 'TechnoSleuths',
  // 'First_Commit',
  // 'QUANTUM STUDY',
  // 'Aethergrid',
  // 'MJDEVS',
  // 'Thala07',
  // 'Envisioneer’s',
  // 'NAVASYA',
  // 'RA-ONE',
  // 'ASMA(The Sky)',
  // 'Triwizard',
  // 'Team Cascaded',
  // 'Tech titans',
  // 'Access Innovators',
  // 'Algorix',
  // 'LOLgorithms',
  // 'AIM',
  // 'XP Innovators',
  // 'AGENTS_101',
  // 'Bubblewrap',
  // 'Codex',
  // 'Arcane',
  // 'ResQTech',
  // 'CoinToss',
  // 'Ultrasonic',
  // 'PhantomDevs',
  // 'TechStrivers',
  // 'Team C.R.A.I',
  // 'LegallyHers',
  // 'CodeRaiders',
  // 'The Loki',
  // 'Tech4Tribe',
  // 'Picapool',
  // 'Perfectly Sane',
  // 'SyntaxSaviors',
  // 'K-Mode',
  // 'Prism',
  // 'Caffeinated Coders',
  // 'CRODERZ',
  // 'Technomad',
  // 'Team IntelleX',
  // 'Syber',
  // 'Ember',
  // 'Lords of the Strings',
  // 'Atomic',
  // 'CodeCrafters',
  // 'Roofsmiths',
  // "Let's begin the hustle",
  // 'Fusion Force',
  // 'AIgents',
  // 'Code & Kebabs',
  // 'QubitGuardians',
  // 'Team Ignitia',
  // 'The Code Warriors',
  // 'GLITCH SQUAD',
  // 'Robotics Addicts',
  // 'HACK OVERFLOW',
  // 'Unknown Coders',
  // 'DevCore',
  // 'HexaCodex',
  // 'Hackronauts',
  // 'Neural Knights',
  // 'CloudCore',
  // 'Metarizz squad',
  // 'Undefined Pair',
  // 'Avengers',
  // 'Ternary',
  // 'ByteForce',
  // 'Elysium',
  // 'MePRO',
  // 'NUTRICHAIN',
  // 'BridgeBack',
  // 'Intelligent Developers Ensemble (IDE)',
  // 'LAZARUS',
  // 'Hacksenberg',
  // 'CodeVizards',
  // 'CodeX',
  // 'Crisis Coders',
  // 'Codestorm',
  // 'Paw patrol',
  // 'localhost',
  // 'Geeks bytes',
  // '404',
  // 'HackHers',
  // 'CodeWizards',
  // 'QuadraCore',
  // 'Hackstreet boys',
  // 'BugsInfinitus',
  // 'SmartMindsTech',
  // 'Team AAA',
  // 'Code Mafia',
  // 'Hack Havoc',
  // 'Code Runners',
  // 'InternConnect',
  // 'CodeVincibles',
  // 'SoloHackR',
  // 'CodeParkerz',
  // 'HexTech',
  // 'Cybertron',
  // 'Group of 5',
  // 'Synapse',
  // 'Cyberescue',
  // 'Los Pollos Hermanos',
  // 'Code Mavericks',
  // 'JAVAans',
  // 'Code fiddlers',
  // 'The Recallers',
  // 'MindMesh',
  // 'VRONTI',
  // 'AI_Avengers',
  // 'Mind Hack Zombies',
  // 'Double Vision',
  // 'MedFlex',
  // 'RAKSHA',
  // 'Re-Wired',
  // 'exit zero',
  // 'Team Connect',
  // 'Pathfinder',
  // 'CANNONCART',
  // 'Just Me.log()',
];

// Configuration for channel prefixes, etc.
export const config = {
  // Channel prefixes
  channelPrefixes: {
    voice: 'team-voice-',
    registration: 'registration',
    modLog: 'mod-log',
    botAudit: 'bot-audit',
  },

  // Category names
  categoryNames: {
    teamVoice: '🎙️ Team Voice Channels',
  },

  // Role prefixes
  rolePrefix: 'Team-',

  // Moderator role name
  moderatorRoleName: 'Moderators',

  // Rate limiting (in milliseconds)
  rateLimits: {
    registration: 30 * 1000, // 30 seconds
  },
};
